# Generated by Django 5.1.4 on 2025-03-19 15:00

from django.db import migrations

from account.scripts import create_group



class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_group(
                group_name='ordenamiento_gestores',
                app_label='urban_management',
                model_name='ordering',
                codenames=['view_ordering', 'change_ordering', 'view_orderingupdate']
            )
        ),
        migrations.RunPython(
            create_group(
                group_name='ordenamiento_operadores',
                app_label='urban_management',
                model_name='ordering',
                codenames=['view_ordering', 'add_orderingupdate', 'view_orderingupdate', 'change_orderingupdate']
            )
        ),
        migrations.RunPython(
            create_group(
                group_name='ordenamiento_inspectores',
                app_label='urban_management',
                model_name='ordering',
                codenames=['add_ordering', 'view_ordering']
            )
        ),
        migrations.RunPython(
            create_group(
                group_name='solicitudes_gestores',
                app_label='issues',
                model_name='issue',
                codenames=['view_issue', 'change_issue', 'view_issueupdate']
            )
        ),
        migrations.RunPython(
            create_group(
                group_name='solicitudes_operadores',
                app_label='issues',
                model_name='issue',
                codenames=['view_issue', 'add_issueupdate', 'view_issueupdate', 'change_issueupdate']
            )
        ),
        migrations.RunPython(
            create_group(
                group_name='voluntariados_gestores',
                app_label='volunteering',
                model_name='volunteering',
                codenames=['add_volunteering', 'view_volunteering', 'change_volunteering', 'view_volunteercategory', 'add_places', 'view_places', 'change_places', 'view_volunteer']
            )
        )
    ]
