# Generated by Django 5.1.4 on 2025-03-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
