# Generated by Django 5.1.4 on 2025-03-13 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_department_position_internaluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaluser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='account.department', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='internaluser',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='account.position', verbose_name='Cargo'),
        ),
    ]
