# Generated by Django 5.1.4 on 2025-03-14 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=8, unique=True)),
                ('category', models.CharField(choices=[('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia'), ('consulta', 'Consulta'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Categoría')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('votes_count', models.IntegerField(default=0, verbose_name='Cantidad de votos')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('recibido', 'Recibido'), ('en proceso', 'En proceso'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='baja', max_length=20, verbose_name='Prioridad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_manager', to='account.internaluser', verbose_name='Gestor')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_operator', to='account.internaluser', verbose_name='Operador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_external_user', to='account.externaluser', verbose_name='Usuario')),
                ('votes', models.ManyToManyField(blank=True, related_name='votes', to='account.externaluser', verbose_name='Votos')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='IssueUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('recibido', 'Recibido'), ('en proceso', 'En proceso'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.issue')),
            ],
            options={
                'verbose_name': 'Actualización de solicitud',
                'verbose_name_plural': 'Actualizaciones de solicitudes',
            },
        ),
    ]
