# Generated by Django 5.1.4 on 2025-02-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='title',
        ),
    ]
