# Generated by Django 5.1.4 on 2025-02-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_issue_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueupdate',
            name='created_at',
        ),
        migrations.AddField(
            model_name='issueupdate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
