# Generated by Django 5.1.4 on 2025-02-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_issue_votes_issue_votes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='uuid',
            field=models.CharField(default='345517ca', max_length=8, unique=True),
        ),
    ]
