# Generated by Django 5.1.4 on 2025-03-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_issue_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='uuid',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
