# Generated by Django 5.1.4 on 2025-03-14 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_externaluser_customuser_is_external'),
        ('issues', '0011_alter_issue_options_alter_issueupdate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='issue',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_operator', to='account.internaluser', verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_manager', to='account.internaluser', verbose_name='Gestor'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='account.externaluser', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='votes', to='account.externaluser', verbose_name='Votos'),
        ),
    ]
