# Generated by Django 5.1.4 on 2025-03-14 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_externaluser_customuser_is_external'),
        ('issues', '0012_remove_issue_assigned_to_issue_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_external_user', to='account.externaluser', verbose_name='Usuario'),
        ),
    ]
