# Generated by Django 5.1.4 on 2025-03-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='category',
            field=models.CharField(blank=True, choices=[('escombros', 'Escombros'), ('ramas', 'Ramas'), ('malezas', 'Malezas'), ('residuos', 'Residuos'), ('vehiculos abandonados', 'Vehículos abandonados'), ('terrenos baldios', 'Terrenos baldios'), ('otro', 'Otro')], max_length=60, verbose_name='Categoría'),
        ),
    ]
