# Generated by Django 5.1.4 on 2025-05-14 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_create_ordering_issues_volunteering_groups'),
        ('urban_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordering',
            name='manager',
        ),
        migrations.CreateModel(
            name='OrderingManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_relations', to='account.internaluser')),
                ('ordering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_relations', to='urban_management.ordering')),
            ],
            options={
                'verbose_name': 'Gestor de ordenamiento',
                'verbose_name_plural': 'Gestores de ordenamientos',
                'unique_together': {('ordering', 'manager')},
            },
        ),
        migrations.AddField(
            model_name='ordering',
            name='managers',
            field=models.ManyToManyField(related_name='managed_orders', through='urban_management.OrderingManager', to='account.internaluser', verbose_name='Gestores'),
        ),
    ]
