# Generated by Django 5.1.4 on 2025-03-13 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_internaluser_department_and_more'),
        ('urban_management', '0002_alter_ordering_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordering',
            name='responsible',
        ),
        migrations.AddField(
            model_name='ordering',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_inspector', to='account.internaluser', verbose_name='Inspector'),
        ),
        migrations.AddField(
            model_name='ordering',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_operator', to='account.internaluser', verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='ordering',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_manager', to='account.internaluser', verbose_name='Gestor'),
        ),
    ]
