# Generated by Django 5.1.4 on 2025-05-16 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_create_ordering_issues_volunteering_groups'),
        ('urban_management', '0002_remove_ordering_manager_orderingmanager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordering',
            name='inspector',
        ),
        migrations.AddField(
            model_name='ordering',
            name='relevador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_relevador', to='account.internaluser', verbose_name='Relevador'),
        ),
    ]
