# Generated by Django 5.1.7 on 2025-07-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_management', '0003_rename_inspector_to_relevador'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordering',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ordenamientos/', verbose_name='Foto'),
        ),
    ]
