# Generated by Django 5.1.4 on 2025-03-13 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_internaluser_department_and_more'),
        ('urban_management', '0003_remove_ordering_responsible_ordering_inspector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderingupdate',
            name='responsible',
        ),
        migrations.AddField(
            model_name='orderingupdate',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_operator_updates', to='account.internaluser', verbose_name='Operador'),
        ),
    ]
