# Generated by Django 5.1.4 on 2025-03-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urban_management', '0004_remove_orderingupdate_responsible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderingupdate',
            name='operator',
        ),
    ]
