# Generated by Django 5.1.4 on 2025-03-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='places',
            options={'verbose_name_plural': 'Places'},
        ),
        migrations.AlterModelOptions(
            name='volunteercategory',
            options={'verbose_name_plural': 'Volunteer Categories'},
        ),
    ]
