# Generated by Django 5.1.4 on 2025-03-10 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteering.volunteering')),
            ],
        ),
    ]
