# Generated by Django 5.1.4 on 2025-03-12 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0002_alter_places_options_alter_volunteercategory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['id'], 'verbose_name': 'Día', 'verbose_name_plural': 'Días'},
        ),
        migrations.AlterModelOptions(
            name='places',
            options={'verbose_name': 'Lugar', 'verbose_name_plural': 'Lugares'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['id'], 'verbose_name': 'Voluntario', 'verbose_name_plural': 'Voluntarios'},
        ),
        migrations.AlterModelOptions(
            name='volunteercategory',
            options={'verbose_name_plural': 'Categorías de voluntariado'},
        ),
        migrations.AlterModelOptions(
            name='volunteering',
            options={'ordering': ['id'], 'verbose_name': 'Voluntariado', 'verbose_name_plural': 'Voluntariados'},
        ),
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='places',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='places',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='places',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='availability',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='motivation',
            field=models.TextField(blank=True, null=True, verbose_name='Motivación'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Habilidades'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteering.volunteering', verbose_name='Voluntariado'),
        ),
        migrations.AlterField(
            model_name='volunteercategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='volunteercategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='volunteercategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='volunteering',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteering.volunteercategory', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='volunteering',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='volunteering',
            name='days',
            field=models.ManyToManyField(to='volunteering.day', verbose_name='Días'),
        ),
        migrations.AlterField(
            model_name='volunteering',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='volunteering',
            name='hours',
            field=models.IntegerField(verbose_name='Horas'),
        ),
        migrations.AlterField(
            model_name='volunteering',
            name='icon',
            field=models.CharField(choices=[('fa-leaf', 'Hoja'), ('fa-hands-helping', 'Manos ayudando'), ('fa-book', 'Libro'), ('fa-heart', 'Corazón'), ('fa-tree', 'Árbol'), ('fa-users', 'Usuarios'), ('fa-seedling', 'Planta'), ('fa-utensils', 'Cubiertos'), ('fa-child', 'Niño'), ('fa-paint-brush', 'Pincel'), ('fa-music', 'Música')], default='fa-heart', help_text='Icono de FontAwesome para mostrar en la tarjeta', max_length=30, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='volunteering',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='volunteering', verbose_name='Imágenes'),
        ),
        migrations.AlterField(
            model_name='volunteering',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteering.places', verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='volunteering',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='volunteering',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
    ]
