# Generated by Django 5.1.4 on 2025-03-14 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_externaluser_customuser_is_external'),
        ('volunteering', '0003_alter_day_options_alter_places_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.externaluser', verbose_name='Usuario'),
        ),
    ]
