# Generated by Django 5.1.4 on 2025-03-14 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_externaluser_customuser_is_external'),
        ('surveys', '0004_alter_answer_options_alter_option_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.externaluser', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='pollster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pollster', to='account.internaluser', verbose_name='Encuestador'),
        ),
    ]
