# Generated by Django 5.1.4 on 2025-03-10 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_survey'),
        ('volunteering', '0002_alter_places_options_alter_volunteercategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='volunteering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='volunteering.volunteering'),
        ),
    ]
